### ISSUE TITLE
Changing zul files reloads the application

### ISSUE THREAD

**Issue by maiconandsilva** [groovyzk/grailszk#8]
Removing `.zul ` files from watched resources may solve the issue. After all, the files should be loaded from file system in development.

**Comment by maiconandsilva** [comment]
To not reload the application when changing the zul files, in `application.yml` add the following:

```yml
spring:
  devtools:
    restart:
      additional-exclude:
        - '*.zul'
        - '**/*.zul'
```
